INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (0,'Standard Kart',0.0,0.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (1,'Pipe Frame',-0.5,0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (2,'Mach 8',0.0,0.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (3,'Steel Driver',0.25,-0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (4,'Cat Cruiser',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (5,'Circuit Special',0.5,-0.75);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (6,'Tri-Speeder',0.25,-0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (7,'Badwagon',0.5,-1.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (8,'Prancer',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (9,'Buggybud',-0.75,0.75);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (10,'Landship',-0.5,0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (11,'Bounder',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (12,'Sports Coupé',0.0,0.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (13,'Gold Kart',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (14,'GLA',0.5,-1.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (15,'W 25 Silver Arrow',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (16,'300 SL Roadster',0.0,0.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (17,'Blue Falcon',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (18,'Tanooki Kart',-0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (19,'B Dasher',0.5,-0.75);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (20,'Streetle',-0.5,0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (21,'P-Wing,0.5',-0.5,-0.75);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (22,'Koopa Clown',-0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (23,'Standard Bike',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (24,'Comet+',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (25,'Sport Bike+',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (26,'The Duke',0.0,0.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (27,'Flame Rider',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (28,'Varmint',-0.5,0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (29,'Mr Scooty',-0.75,0.75);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (30,'Jet Bike+',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (31,'Yoshi Bike+',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (32,'Master Cycle+',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (33,'City Tripper',-0.5,0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (34,'Standard Quad',0.5,-1.0);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (35,'Wild Wiggler',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (36,'Teddy Buggy',-0.25,0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (37,'Bone Rattler',0.25,-0.5);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (38,'Splat Buggy',0.25,-0.25);
INSERT INTO Vehicle (id,name,speed,acceleration) VALUES (39,'Inkstriker',0.0,0.0);
